### PR TITLE
Reduce docker image size

### PR DESCRIPTION
**Pull request by Lbird**
Use multi-stage build.

### CODE REVIEW

**Comment by kwjooo** [comment]
Is there any reasons why you use alpine3.7 instead of 3.9?

**Comment by Lbird** [comment]
> Is there any reasons why you use alpine3.7 instead of 3.9?

No special reason. Just to match the version to tendermint's docker image.

**Comment by kwjooo** [comment]
Accroding to [this](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases)
The end support date of alpine v3.7 is 2019-11-01..
So we want to use alpine v3.9!
Please modify alpine version from v3.7 to v3.9!

**Comment by Lbird** [comment]
Done as you requested.

**Pull request merged**
